// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package errors

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsDefaultErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DEFAULT_ERR.String() && e.Code == 400
}

func ErrorDefaultErr(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_DEFAULT_ERR.String(), fmt.Sprintf(format, args...))
}

func IsOkErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OK_ERR.String() && e.Code == 200
}

func ErrorOkErr(format string, args ...interface{}) *errors.Error {
	return errors.New(200, ErrorReason_OK_ERR.String(), fmt.Sprintf(format, args...))
}
