// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/china-xs/gin-tpl/example/blog/internal/server"
	"github.com/china-xs/gin-tpl/example/blog/internal/service/auth"
)

// Injectors from wire.go:

// cf config path
func initApp() (*server.Route, func(), error) {
	loginService := auth.NewLoginService()
	route := &server.Route{
		SrvLogin: loginService,
	}
	return route, func() {
	}, nil
}
