// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOaDepartments = "oa_departments"

// OaDepartments mapped from table <oa_departments>
type OaDepartments struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PID       int32     `gorm:"column:p_id;not null;default:0" json:"p_id"`             // 上级部门
	LeaderID  int32     `gorm:"column:leader_id;not null;default:0" json:"leader_id"`   // 部门负责人
	RoleID    int32     `gorm:"column:role_id;not null;default:0" json:"role_id"`       // 部门的默认角色id
	Title     string    `gorm:"column:title;not null" json:"title"`                     // 部门名称
	OrderNum  int32     `gorm:"column:order_num;not null;default:0" json:"order_num"`   // 排序 order_num asc,created_at asc
	Remark    string    `gorm:"column:remark;not null" json:"remark"`                   // 备注
	PIds      string    `gorm:"column:p_ids;not null" json:"p_ids"`                     // 上级所有ids
	OperateID int32     `gorm:"column:operate_id;not null;default:0" json:"operate_id"` // 最后更新人
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`           // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`           // 更新时间
}

// TableName OaDepartments's table name
func (*OaDepartments) TableName() string {
	return TableNameOaDepartments
}
